package life.qbic.registration.types

/**
 * <p>Controlled vocabulary for openBIS dataset types</p>
 *
 * @since 1.0.0
 */
enum QDatasetType {
    Q_WF_LX_MHC_QUANTIFICATION_RESULTS,
    Q_WF_MX_IDENTIFY_AND_QUANTIFY_RESULTS,
    Q_WF_NGS_16S_AMPLICON_SEQ_RESULTS,
    Q_WF_NGS_ATAC_SEQ_RESULTS,
    Q_WF_NGS_ANCIENT_DNA_SEQ_RESULTS,
    Q_WF_NGS_BCELL_REPERTOIRE_SEQ_RESULTS,
    Q_WF_NGS_CHIP_SEQ_RESULTS,
    Q_WF_NGS_HLATYPING_RESULTS,
    Q_WF_NGS_METHYLATION_ANALYSIS_RESULTS,
    Q_WF_NGS_RNAEXPRESSIONANALYSIS_RESULTS,
    Q_WF_NGS_RNA_SEQ_RESULTS,
    Q_WF_NGS_SCELL_RNA_SEQ_RESULTS,
    Q_WF_NGS_SHOTGUN_METAGENOMICS_RESULTS,
    Q_WF_NGS_SMALL_RNA_SEQ_RESULTS,
    Q_WF_NGS_VARIANT_CALLING_RESULTS
}
