package life.qbic.registration.types

/**
 * <p>Controlled vocabulary for openBIS experiment types</p>
 *
 * @since 1.0.0
 */
enum QExperimentType {
    Q_WF_LX_MHC_QUANTIFICATION,
    Q_WF_MS_MAXQUANT,
    Q_WF_MX_IDENTIFY_AND_QUANTIFY,
    Q_WF_NGS_16S_AMPLICON_SEQ,
    Q_WF_NGS_ATAC_SEQ,
    Q_WF_NGS_ANCIENT_DNA_SEQ,
    Q_WF_NGS_BCELL_REPERTOIRE_SEQ,
    Q_WF_NGS_CHIP_SEQ,
    Q_WF_NGS_HLATYPING,
    Q_WF_NGS_METHYLATION_ANALYSIS,
    Q_WF_NGS_RNA_EXPRESSION_ANALYSIS,
    Q_WF_NGS_RNA_SEQ,
    Q_WF_NGS_SCELL_RNA_SEQ,
    Q_WF_NGS_SHOTGUN_METAGENOMICS,
    Q_WF_NGS_SMALL_RNA_SEQ,
    Q_WF_NGS_VARIANT_CALLING
}
