package life.qbic.registration.types

/**
 * <p>Controlled vocabulary for openBIS sample types</p>
 *
 * @since 1.0.0
 */
enum QSampleType {
    Q_WF_LX_MHC_QUANTIFICATION_RUN,
    Q_WF_MX_IDENTIFY_AND_QUANTIFY_RUN,
    Q_WF_NGS_ATAC_SEQ_RUN,
    Q_WF_NGS_ANCIENT_DNA_SEQ_RUN,
    Q_WF_NGS_BCELL_REPERTOIRE_SEQ_RUN,
    Q_WF_NGS_CHIP_SEQ_RUN,
    Q_WF_NGS_HLATYPING_RUN,
    Q_WF_NGS_METHYLATION_ANALYSIS_RUN,
    Q_WF_NGS_RNA_EXPRESSION_RUN,
    Q_WF_NGS_RNA_SEQ_RUN,
    Q_WF_NGS_SCELL_RNA_SEQ_RUN,
    Q_WF_NGS_SHOTGUN_METAGENOMICS_RUN,
    Q_WF_NGS_SMALL_RNA_SEQ_RUN,
    Q_WF_NGS_VARIANT_CALLING_RUN
}